group: travis_latest
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  'on':
    tags: true
  email:
    secure: >-
      F59kKHE6nLgCvGU/J4QgaCCg2OL8y8YOpw6B0sh4X1ajmKkN5D66/rpTvNrKi/iJlEDjYajQKSCB3QOLChqvmiMku2LBs5mMOxBHRYDgk38m+BFLP1oscQUt2N/dL7NBH1iqy6HXYaKlTGGUfWvhSBVWYcUUPUe4EPy1KXtL+Py1EycqIhjgB0A2pvmQ2hDCK1DN3PJaaeSSKhyUizmmR68wI9+73xrysWe4HUGZwrhvm9QYETDfNWc4a7j1s73yUSd7q16BGDVyltb8+5U9mG2a1+tpA5nHG9sn/nUna/qYUfIawtlDRwYf9or76osP1kVSsgVYmkwu6eATZY3RdQFOAtZTvDGGOjvZy+S6H6fcYSI4ciZlLESJi4MxkxdZznf+Jb6SdshY/BjEMnyRt5MrF+4jAS2uf0zsNvcLeaQ0x3K33j497IV43E21hboPBOVYu5cJm23jmOHvokMPF+A1y3k+IvlSxAts6MfAABvy0i42wL67l5H0G0RAtidN25BH4Ld0UnH4/PLHyg7NYdIjoIaj/3S7pYICLHcWCopRH5ZOfaloUx4YONJhbjneMMNkOLaHAaRu0C8TsgRi4jGBWVM+kQsVq5FD6mk/Y/UYNqPtwIGyFEp3mPMz5FS8qgN6VGby2zI2EzBzH3IBFMkNnMJeRvOzLNVRh8NOcP0=
  api_key:
    secure: >-
      C8qBI8A+2jgsVDGaGTI85akZZ/piWN6xRNz3o1hCYKAij6zz2NvCxDlQyNz2jxoM1f3LYBgbPXyDXSzVOozCrJjRuXGFzcyU0hmCAuoNg6LI3K6KRQwxsfT0X/k7YtRVRmB9VlsKZF0yCGoCbxRoQR2ZGfYmGh23Cru4kWCILISw9QnvMr3M3AW0D9xJ+2ADdufko5x0iihFJ0Yu2mpcehQszLZ+YpAPNb61rtAnEkw+tKUh3RYinwA034VuQrIuBolGaqLQdQ+JB1+c0ZED4qemDmRWfNxKnVRL4d3JLXoWYG1XTZ01ykZ8UTIp3oNyF0aZ741NlbY18EHHhAGS8PJeRILlT/LGmelw4zWFdz1vjkfPmMcAvRb0uvZkqP5SC1siKqOiqWUXD8gqt2YzrzTvmh/YY/XJnwS9w88Xy3SjhBfM03b/DBwv25+2bA6sGBRWlTFwjrbTvcnFOsVasnOoCHu/vtAX9sr88co/wHP8NSjeBCPwdQmzhsPTDsLhxzPrSTbw/IGMq3Ah00CRJnCltqRIhcXBAYseyacjFARWpWvVkANVxPeT+9x8Q+eUMj/jbY9QjS0jTUmQaD79GDWYkKMRmXd8aZ0aifDJX5v7YNmM/HLTR6syhRpiToVi4E5MZrpflgExdmFneHEDZDdB/5GvBlM/mTTIoLzsyVA=
